apiVersion: apps/v1
kind: Deployment
metadata:
    name: moderation-depl
spec:
    replicas: 1 #number of pods
    selector:
        matchLabels: # find all pods with label 'moderation'
            app: moderation
    template:
        metadata:
            labels: #labels pods being created (matches matchLabels)
                app: moderation
        spec:
            containers:
                - name: moderation
                  image: landen1221/moderation
---
apiVersion: v1
kind: Service
metadata:
    name: moderation-srv
spec:
    selector:
        app: moderation
    type: ClusterIP
    ports:
        - name: moderation
          protocol: TCP
          port: 4003
          targetPort: 4003
