apiVersion: apps/v1
kind: Deployment
metadata:
    name: posts-depl
spec:
    replicas: 1 #number of pods
    selector:
        matchLabels: # find all pods with label 'posts'
            app: posts
    template:
        metadata:
            labels: #labels pods being created (matches matchLabels)
                app: posts
        spec:
            containers:
                - name: posts
                  image: landen1221/posts
---
apiVersion: v1
kind: Service
metadata:
    name: posts-clusterip-srv
spec:
    selector:
        app: posts
    type: ClusterIP
    ports:
        - name: posts
          protocol: TCP
          port: 4000
          targetPort: 4000
