apiVersion: apps/v1
kind: Deployment
metadata:
    name: query-depl
spec:
    replicas: 1 #number of pods
    selector:
        matchLabels: # find all pods with label 'query'
            app: query
    template:
        metadata:
            labels: #labels pods being created (matches matchLabels)
                app: query
        spec:
            containers:
                - name: query
                  image: landen1221/query
---
apiVersion: v1
kind: Service
metadata:
    name: query-srv
spec:
    selector:
        app: query
    type: ClusterIP
    ports:
        - name: query
          protocol: TCP
          port: 4002
          targetPort: 4002
